
import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "@/components/Navigation"; 
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: {
  children: React.ReactNode;
}) {
  const navItems = [
    { title: 'Home', href: '/' },
    { title: 'About', href: '/about' },
    { title: 'Contact', href: '/contact' },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
     
        <header>
          <Navigation items={navItems} />
        </header>
        <main className="max-w-[1300px] mx-auto px-5">
          <div>{children}</div>         
        </main>
      </body>
    </html>
  );
}
